#!/bin/bash

set -eu

sudo apt-get install -q -y charm-helper-sh

[ -f /usr/share/charm-helper/bash/file.bash ] && . /usr/share/charm-helper/bash/file.bash || . lib/ch-file.sh
. /usr/share/charm-helper/sh/net.sh

RELEASE=$(config-get release)
ADMIN_USERNAME=$(config-get username)
ADMIN_PASSWORD=$(config-get password)
CWD=$(dirname $0)
JENKINS_HOME=/var/lib/jenkins

JENKINS_VERSION=`dpkg -p jenkins | grep Version | awk '{print $2}' | sed 's/\+.*//'`

setup_jenkins_source () {
  # Do something with < Oneiric releases - maybe PPA
  #  apt-get -y install python-software-properties
  #  add-apt-repository ppa:hudson-ubuntu/testing
  juju-log "Configuring source of jenkins as $RELEASE"
  # Configure to use upstream archives
  # lts - debian-stable
  # trunk - debian
  case $RELEASE in
    distro)
      # don't setup upstream source, install from archive
      # only good for oneiric
      return 0;;
    lts)
      SOURCE="debian-stable";;
    trunk)
      SOURCE="debian";;
    ppa:*)
      juju-log "Configuring $RELEASE"
      add-apt-repository -y $RELEASE
      apt-get update || true
      JENKINS_VERSION=`dpkg -p jenkins | grep Version | awk '{print $2}' | sed 's/\+.*//'`
      return 0;;
    *)
      juju-log "release configuration not recognised" && exit 1;;
  esac
  # Setup archive to use appropriate jenkins upstream
  wget -q -O - http://pkg.jenkins-ci.org/$SOURCE/jenkins-ci.org.key | apt-key add -
  echo "deb http://pkg.jenkins-ci.org/$SOURCE binary/" \
      > /etc/apt/sources.list.d/jenkins.list
  chmod 644 /etc/apt/sources.list.d/*
  apt-get update || true
  JENKINS_VERSION=`dpkg -p jenkins | grep Version | awk '{print $2}' | sed 's/\+.*//'`
}
# Only setup the source if jenkins is not already installed
# this makes the config 'release' immutable - i.e. you 
# can change source once deployed
[[ -d $JENKINS_HOME ]] || setup_jenkins_source

# Install jenkins
install_jenkins () {
  juju-log "Installing/upgrading jenkins..."
  apt-get -y install -qq jenkins
}
# Re-run whenever called to pickup any updates
install_jenkins

configure_jenkins_user () {
  juju-log "Configuring user for jenkins..."
  # Generate Salt and Hash Password for Jenkins
  SALT="$(< /dev/urandom tr -dc A-Za-z | head -c6)"
  PASSWORD="$SALT:$(echo -n "$ADMIN_PASSWORD{$SALT}" | shasum -a 256 | awk '{ print $1 }')"
  mkdir -p $JENKINS_HOME/users/$ADMIN_USERNAME
  sed -e s#__USERNAME__#$ADMIN_USERNAME# -e s#__PASSWORD__#$PASSWORD# \
	  $CWD/../templates/user-config.xml > $JENKINS_HOME/users/$ADMIN_USERNAME/config.xml
  chown -R jenkins:nogroup $JENKINS_HOME/users
}
# Always run - even if config has not changed, its safe
configure_jenkins_user

boostrap_jenkins_configuration () {
  juju-log "Bootstrapping secure initial configuration in Jenkins..."
  cp $CWD/../templates/jenkins-config.xml $JENKINS_HOME/config.xml
  chown jenkins:nogroup $JENKINS_HOME/config.xml
  touch /var/lib/jenkins/config.bootstrapped
}
# Only run on first invocation otherwise we blast
# any configuration changes made
[[ -f /var/lib/jenkins/config.bootstrapped ]] || boostrap_jenkins_configuration

install_plugin() {
  local plugin_url=$1
  #TODO local check_cert=`config-get plugins-check-certificate`

  juju-log "Installing $plugin_url"
  ( cd $JENKINS_HOME/plugins && wget --no-check-certificate --timestamping -q $plugin_url )
  juju-log "got it"
}

install_core_plugins() {
  local core_plugins=`config-get core-plugins`
  for plugin in $core_plugins ; do
    install_plugin "http://mirrors.jenkins-ci.org/plugins/$plugin/$JENKINS_VERSION/$plugin.hpi"
  done
}

install_user_plugins() {
  local plugins_site=`config-get plugins-site`
  local plugins=`config-get plugins`
  for plugin in $plugins ; do
    install_plugin "$plugins_site/latest/$plugin.hpi"
  done
}

install_plugins() {
  juju-log "Installing plugins"

  mkdir -p $JENKINS_HOME/plugins
  chmod a+rx $JENKINS_HOME/plugins

  install_core_plugins # "core" plugins must match jenkins version exactly
  install_user_plugins

  # Hack only for this charm...
  install_plugin "http://updates.jenkins-ci.org/download/plugins/build-publisher/1.12/build-publisher.hpi"

  chown -Rf jenkins:nogroup $JENKINS_HOME/plugins/*.hpi
  chmod a+r $JENKINS_HOME/plugins/*.hpi

  #TODO local remove_unlisted_plugins=`config-get remove-unlisted-plugins`
}
install_plugins

configure_ircbot() {
  local ircbot_server=$(config-get ircbot_server)
  local ircbot_port=$(config-get ircbot_port)
  local ircbot_ssl=$(config-get ircbot_ssl)
  local ircbot_nick=$(config-get ircbot_nick)
  local ircbot_password=$(config-get ircbot_password)
  local ircbot_channel=$(config-get ircbot_channel)
  local ircbot_channel_password=$(config-get ircbot_channel_password)
  local irc_config_file="hudson.plugins.ircbot.IrcPublisher.xml"
  ch_template_file 755 \
                   jenkins:nogroup \
                   templates/$irc_config_file \
                   $JENKINS_HOME/$irc_config_file \
                   "ircbot_enabled ircbot_server ircbot_port ircbot_ssl ircbot_nick ircbot_password ircbot_channel ircbot_channel_password"
  local jenkins_address=$(unit-get public-address)
  #local jenkins_url="http://$jenkins_address:8080/"
  local jenkins_url="https://jenkins.qa.ubuntu.com/"
  local url_config_file="hudson.tasks.Mailer.xml"
  ch_template_file 755 \
                   jenkins:nogroup \
                   templates/$url_config_file \
                   $JENKINS_HOME/$url_config_file \
                   "jenkins_url"
}

configure_build_publisher() {
  local build_publisher_url=$(config-get build_publisher_url)
  local build_publisher_username=$(config-get build_publisher_username)
  local build_publisher_password=$(config-get build_publisher_password)
  local config_file="hudson.plugins.build_publisher.BuildPublisher.xml"
  ch_template_file 755 \
                   jenkins:nogroup \
                   templates/$config_file \
                   $JENKINS_HOME/$config_file \
                   "build_publisher_url build_publisher_username build_publisher_password"

}

configure_plugins() {
  local ircbot_enabled=$(config-get ircbot_enabled)
  [ -z "$ircbot_enabled" ] || configure_ircbot

  local build_publisher_enabled=$(config-get build_publisher_enabled)
  [ -z "$build_publisher_enabled" ] || configure_build_publisher

}
configure_plugins


# Install helpers  - python jenkins ++
install_python_jenkins () {
  juju-log "Installing python-jenkins..."
	# Pickup backports as required for natty
  add-apt-repository ppa:python-jenkins-developers/backports
  # Might not pickup for current release - so ignore errors
  apt-get update || true
  apt-get -y install -qq python-jenkins
}
# Only install once
[[ -d /usr/share/pyshared/jenkins ]] || install_python_jenkins

# Install some tools - can get set up deployment time
install_tools () {
  juju-log "Installing tools..."
  apt-get -y install -qq `config-get tools`
}
# Always run - tools might get re-configured
install_tools

generate_api_token() {
  TOKEN=$(echo $ADMIN_PASSWORD | shasum | awk '{ print $1 }')
  echo $TOKEN > $JENKINS_HOME/API_TOKEN
  chown jenkins:nogroup $JENKINS_HOME/API_TOKEN
}
[ -f "$JENKINS_HOME/API_TOKEN" ] || generate_api_token

install_juju() {
  juju-log "installing/updating juju test components"
  [ -f lib/juju-test-tools.sh ] && . lib/juju-test-tools.sh && install_juju_test_tools jenkins $JENKINS_HOME

  juju-log "installing/updating juju client components"
  [ -f lib/juju-client.sh ] && . lib/juju-client.sh && install_juju_client jenkins $JENKINS_HOME

  INSTALL_CHARM_TESTS=$(config-get install_charm_tests)
  if [ -n "$INSTALL_CHARM_TESTS" ]; then
    juju-log "creating/updating jenkins jobs for charms"
    [ -f lib/charm-job.sh ] && . lib/charm-job.sh && update_charm_jobs jenkins $JENKINS_HOME
  fi
  juju-log "done installing juju"
  juju-log "installing jenkins-cli tool"
  rsync -avz files/jenkins-cli.jar $JENKINS_HOME/
}
install_juju

juju-log "Restarting jenkins to pickup configuration changes"
service jenkins restart

juju-log "Opening ports"
open-port 8080

exit 0
