#!/bin/bash

service jenkins start || true

RUN_CHARM_TESTS=$(config-get run_charm_tests)
if [ -n "$RUN_CHARM_TESTS" ]; then
  juju-log "creating/updating jenkins jobs for charms"
  echo "sudo -HEsu jenkins /var/lib/jenkins/bin/run-charm-jobs > /var/lib/jenkins/run.log 2>&1" | at now + 10 minutes 
fi

