#!/bin/bash
set -eu

usage() {
  echo "usage: $0 <charm_name>"
  echo "  'charm_name' is the charm to test"
  echo "will run any tests found in the charm's /tests directory in lexicographical order"
  exit 1
}
(( $# == 1 )) || usage

timestamp() {
  date +"%G-%m-%d-%H%M%S"
}

setup() {
  echo "setting up test"

  echo "cleaning up any previous environments"
  yes | sudo juju destroy-environment; echo

  echo "wait around a bit for security groups to flush"
  sleep 60
}

run_unit_test() {
  local unit_test=$1
  echo "running $unit_test at $(timestamp)"

  $HOME/charms/precise/$charm_name/tests/$unit_test

  echo "finished $unit_test at $(timestamp)"
}

run_tests() {
  echo "running unit tests at $(timestamp)"
  if [ -d $HOME/charms/precise/$charm_name/tests ]; then
    for unit_test in `ls $HOME/charms/precise/$charm_name/tests`; do
      run_unit_test $unit_test
      #if [ -x $unit_test ]; then
      #  run_unit_test $unit_test
      #fi
      # if it's a dir... do something different
    done
  else
    echo "no unit tests for $charm_name"
  fi
  echo "done running unit tests at $(timestamp)"
}

archive_logs() {
  local destination=$1
  $HOME/bin/juju-slurp-logs --dir $destination/logs || mkdir -p $destination/logs
  ( cd $destination && tar czvf $destination/$(basename $0)-logs.tar.gz logs )
  sudo chown -Rf jenkins.nogroup $destination
}

archive_charm() {
  local destination=$1
  if [ -d $HOME/charms/precise/$charm_name ]; then
    ( cd $HOME/charms/precise/$charm_name ; bzr revno > $destination/charm-revision ) # need to add to archive
    ( cd $HOME/charms/precise/$charm_name ; zip -r $destination/charm-$charm_name.zip . )
  fi
}

fail() {
  echo "test failed"
  exit 1
}

teardown() {
  echo "archiving charm"
  archive_charm $WORKSPACE
  echo "archiving logs"
  archive_logs $WORKSPACE
  echo "tearing down test"
  yes | sudo juju destroy-environment; echo
}

for arg; do
  charm_name=$arg
done

trap teardown EXIT INT TERM
setup
run_tests
trap - EXIT INT TERM

teardown
exit 0

