#!/usr/bin/env python

import sys
import json
import requests

BASE_URL="http://jenkins.qa.ubuntu.com/job/%s/lastBuild/api/json"
request = requests.get( BASE_URL % sys.argv[1] )
print json.loads(request.text)["number"]

