#!/bin/bash
set -eu

usage() {
  echo "usage: $0 release"
  echo "will pre-cache a juju lxc environment"
  exit 1
}
(( $# == 1 )) || usage

bootstrap() {
  sudo juju bootstrap || true
  # leave it up
}

setup() {
  echo "setting up test"
  #juju-snapshot snapshot -elocal -f $HOME/precache-pristine-state.json
}

generate_lxc_cache() {
  echo "generating lxc cache..."
  juju deploy mysql

  timeout 1800s /var/lib/jenkins/bin/watch-for-service-started mysql/0 && echo "pass" || fail
}

fail() {
  echo "precaching failed"
  exit 1
}

teardown() {
  echo "tearing down"
  #juju-snapshot restore -f $HOME/precache-pristine-state.json
  yes | sudo juju destroy-environment; echo
}

bootstrap

trap teardown EXIT INT TERM
setup
generate_lxc_cache
trap - EXIT INT TERM

teardown
exit 0

