#!/bin/bash
set -eu

usage() {
  echo "usage: $0 release"
  echo "will pre-cache a juju lxc environment"
  exit 1
}
(( $# == 1 )) || usage

bootstrap() {
  juju bootstrap || true
  # leave it up
}

setup() {
  echo "setting up test"
  #juju-snapshot snapshot -elocal -f $HOME/precache-pristine-state.json
}

generate_lxc_cache() {
  echo "generating lxc cache..."
  juju deploy --repository $HOME/charms local:mysql

  #$HOME/bin/juju-service-started mysql 2> /dev/null && echo "pass" || fail
  juju-watch mysql && echo "pass" || fail
}

fail() {
  echo "precaching failed"
  exit 1
}

teardown() {
  echo "tearing down"
  #juju-snapshot restore -f $HOME/precache-pristine-state.json
  yes | juju destroy-environment
}

bootstrap

trap teardown EXIT INT TERM
setup
generate_lxc_cache
trap - EXIT INT TERM

teardown
exit 0

