#!/bin/bash

timestamp() {
  date +"%G-%m-%d-%H%M%S"
}

usage() {
  echo "usage: $0"
  echo "  will run all jenkins jobs for charm tests"
  echo "will run tests against the user's default juju environment"
  echo "JENKINS_HOME must be set"
  exit 1
}
[ -n "$JENKINS_HOME" ] || usage


echo "running charm tests: $(timestamp)"

for job_name in `ls $JENKINS_HOME/jobs`
do
  $JENKINS_HOME/bin/run-charm-job $job_name
done

echo "done: $(timestamp)"
