#!/bin/bash

API_TOKEN=`cat $HOME/API_TOKEN`

timestamp() {
  date +"%G-%m-%d-%H%M%S"
}

echo "running charm tests: $(timestamp)"

for job in `ls $HOME/jobs`
do
  curl http://localhost:8080/job/$job/build?token=$API_TOKEN
done

echo "done: $(timestamp)"
